[meta]
title = "d -云端内容示例"

["114514种论证"]
export = true
visible = true
options = [
  "zhen",
  "j",
]
# 开启云内容
cloud_extra = true
# 云内容与本地内容去重
dictinct = true
# 云内容链接
options_urls = [
  "https://api.github.com/Chencyyy/sealdice/blob/main/test.toml",
]
