[meta]
title = "野兽牌堆"
updateUrls = [
  "https://ghp.ci/https://raw.githubusercontent.com/Chencyyy/sealdice/main/test.toml" # 此处填写你的更新链接
]

# 简单牌组表
[decks]
"快端上来罢" = [
  "哼哼哼啊啊啊啊啊",
  "你是一个一个一个牌堆结果"
]

# 复杂牌组
["数字论证"]
export = true
visible = true
aliases = [ "恶臭论证" ]
options = [
  "114514",
  "1919810",
]
